### ISSUE TITLE
Buttons in footer

### ISSUE THREAD

**Issue by boogdann** [boogdann/Cafe#7]
Buttons in footer are not clickable
![image](https://github.com/boogdann/Cafe/assets/118774688/7a70ca7b-6593-4f4b-87c7-23a9a4b34427)

**Comment by Egor123qwe** [comment]
а как они должны быть кликэбэл?

**Comment by boogdann** [comment]
ну как минимум переносить на какую-то часть страниицы, выделяться при наведении и + ссылки на соц.сети (перенос по странице уже сделал)
